# Generated by Django 5.2.15 on 2026-07-06 15:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adapter', models.CharField(max_length=50)),
                ('operation', models.CharField(max_length=50)),
                ('dedup_key', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('request', models.JSONField(blank=True, default=dict)),
                ('response', models.JSONField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('external_ref', models.CharField(blank=True, max_length=200)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.tenant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tenant', 'dedup_key'), name='uniq_integrationtx_tenant_dedup')],
            },
        ),
        migrations.CreateModel(
            name='NumberSequence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=50)),
                ('last_value', models.BigIntegerField(default=0)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.tenant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tenant', 'key', 'branch'), name='uniq_numbersequence_tenant_key_branch', nulls_distinct=False)],
            },
        ),
    ]
